name: Admin Panel - Add New App

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'ناوی یاری یان بەرنامە (نموونە: Block Blast)'
        required: true
      app_version:
        description: 'ڤێرژن (نموونە: 1.0.0)'
        required: true
      app_size:
        description: 'قەبارە (نموونە: 150 MB)'
        required: true
      app_icon:
        description: 'ناوی وێنەکە یان لینک (نموونە: logo.png)'
        required: true
      ipa_link:
        description: 'لینکی ڕاستەوخۆی دابەزاندنی IPA'
        required: true

jobs:
  add_app:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Admin Script
        env:
          APP_NAME: ${{ github.event.inputs.app_name }}
          APP_VERSION: ${{ github.event.inputs.app_version }}
          APP_SIZE: ${{ github.event.inputs.app_size }}
          APP_ICON: ${{ github.event.inputs.app_icon }}
          IPA_LINK: ${{ github.event.inputs.ipa_link }}
        run: python admin_adder.py

      - name: Upload IPA to Release V1
        uses: softprops/action-gh-release@v1
        with:
          tag_name: V1
          files: ipas/*.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update JSON Source
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add ashtemobile94.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Admin added: ${{ github.event.inputs.app_name }}" && git push)
