name: Auto Website Downloader

on:
  workflow_dispatch:
    inputs:
      website_link:
        description: 'لینکی ماڵپەڕەکەت لێرە دابنێ'
        required: true
        default: 'https://ashtemobile.tututweak.com/o.html'

jobs:
  sync_from_website:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run Auto Extractor Script
        env:
          WEBSITE_URL: ${{ github.event.inputs.website_link }}
        run: python auto_extractor.py

      - name: Upload IPAs to Release V1
        uses: softprops/action-gh-release@v1
        with:
          tag_name: V1
          files: ipas/*.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push JSON files
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add ashtemobile94.json backup_memory.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-Downloaded from website!" && git push)
