name: Admin Panel - Add Bulk Apps

on:
  workflow_dispatch:
    inputs:
      bulk_data:
        description: 'لێرەدا یارییەکان دابنێ. (نموونە: ناو | ڤێرژن | قەبارە | وێنە | لینک)'
        required: true
        type: string

jobs:
  add_apps:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Admin Script
        env:
          BULK_DATA: ${{ github.event.inputs.bulk_data }}
        run: python admin_adder.py

      - name: Upload IPAs to Release V1
        uses: softprops/action-gh-release@v1
        with:
          tag_name: V1
          files: ipas/*.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update JSON Source, Memory, and Images
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add ashtemobile94.json backup_memory.json img/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Admin added multiple apps successfully!" && git push)
